
exports.TOKEN = 'NjQ0MTg0MzU1NDg0MjA1MDY3.Xc_tNg.Vh2BPfBRIR_mn6mdC27LmNS8p1Q'; //THIS BOT IS FOR MULTIPLE GUILD
exports.PREFIX = '.';

exports.GOOGLE_API_KEY = 'AIzaSyC8GHxFJ17uRpUYuyUngZ4lrlWNV_P85-w';
exports.COLOR = '#fffff';
exports.STATUS = `YOUR STATUS`;