
exports.TOKEN = 'NjQ0MTg0MzU1NDg0MjA1MDY3.XdEAZg.CKt87YPjhyAMZVGrbCNxMDQHZVU'; //THIS BOT IS FOR MULTIPLE GUILD
exports.PREFIX = '.';

exports.GOOGLE_API_KEY = 'AIzaSyC8GHxFJ17uRpUYuyUngZ4lrlWNV_P85-w';
exports.COLOR = '#fffff'; //COLOR OF EMBED
exports.STATUS = `YOUR STATUS`; //ADD YOUR BOT STATUS
